### ISSUE TITLE
Signup via GitHub broken

### ISSUE THREAD

**Issue by jayvdb** [ScalaWilliam/git-work#27]
During signup, after doing the http://indieauth.com thing , I find myself on page `https://git.work/callback/?code=...` , and the page source is only the literal value `GET https://git.work/callback/?code=...` with a slightly different URL.

**Comment by ScalaWilliam** [comment]
It's still work in progress. I evaluated the system and decided git.work will be much simpler as a dumb aggregator of various 'work' feeds/websites, such as http://work.scalawilliam.com/.

In such instance, it will not be necessary to sign up at all. I'm trying to keep it more lean than originally intended.

Apologies for unclear/out-of-date information.

**Comment by jayvdb** [comment]
Close and create another forum to discuss design?

If it is 'dumb', it cant lock in allocations. Without a temporary lock, devs will be reluctant to start a job that someone else may have already finished.

**Comment by ScalaWilliam** [comment]
Understood.
Posted here. https://github.com/ScalaWilliam/git-work/issues/28

**Comment by ScalaWilliam** [comment]
Btw thanks a lot @jayvdb  :)
